# Matrix Implementation
## Matrix Operation :

#### 1.Addition & Subtraction on Matrix

In [2]:
import numpy as np
# sales Marix of ice-cream
a_sales=np.array([
    [200,304,590],
    [100,250,150],
    [1000,500,300]
])

b_sales=np.array([
    [600,500,400],
    [340,200,506],
    [200,866,900],
])

# matirx addition
total_sales=a_sales+b_sales

print("Sales of A:\n",a_sales)
print("Sales of B:\n",b_sales)
print("Total Sales:\n",total_sales)

print("====="*10)
reduced_sales=a_sales-b_sales
print("Reduced Sales:\n",reduced_sales)

Sales of A:
 [[ 200  304  590]
 [ 100  250  150]
 [1000  500  300]]
Sales of B:
 [[600 500 400]
 [340 200 506]
 [200 866 900]]
Total Sales:
 [[ 800  804  990]
 [ 440  450  656]
 [1200 1366 1200]]
Reduced Sales:
 [[-400 -196  190]
 [-240   50 -356]
 [ 800 -366 -600]]


In [4]:
import torch
vipul_sales=torch.tensor([
    [150.,140.2,47.8],
    [474.3,484.,484.8],
    [384.3,584.47,595.48]
])

brijesh_sales=torch.tensor([
    [495.49,484,394.398],
    [953.39,430.39,283.38],
    [490.39,494.3,948.4]
])

# Total Sales
total_sales_pt=torch.add(vipul_sales,brijesh_sales)

# Reduced Sales
reduced_sales_pt=brijesh_sales-vipul_sales

print("Vipul sales:\n",vipul_sales)
print("Brijesh sales:\n",brijesh_sales)
print("Total sales:\n",total_sales_pt)
print("Reduced Sales:\n",reduced_sales_pt)

Vipul sales:
 tensor([[150.0000, 140.2000,  47.8000],
        [474.3000, 484.0000, 484.8000],
        [384.3000, 584.4700, 595.4800]])
Brijesh sales:
 tensor([[495.4900, 484.0000, 394.3980],
        [953.3900, 430.3900, 283.3800],
        [490.3900, 494.3000, 948.4000]])
Total sales:
 tensor([[ 645.4900,  624.2000,  442.1980],
        [1427.6899,  914.3900,  768.1800],
        [ 874.6900, 1078.7700, 1543.8800]])
Reduced Sales:
 tensor([[ 345.4900,  343.8000,  346.5980],
        [ 479.0900,  -53.6100, -201.4200],
        [ 106.0900,  -90.1700,  352.9200]])


### 2.Scaler Multiplication

In [6]:
import numpy as np
cost=np.array([2000,4738.38,2928.48])
gst=0.18

# increased Price after gst
gst_price=gst*cost
total_price=gst_price+cost

print("Cost:\n",cost)
print("Gst:\n",gst)
print("Gst_price:\n",gst_price)
print("Total Price with gst:\n",total_price)

Cost:
 [2000.   4738.38 2928.48]
Gst:
 0.18
Gst_price:
 [360.     852.9084 527.1264]
Total Price with gst:
 [2360.     5591.2884 3455.6064]


In [9]:
import torch
cost_pt=torch.tensor([50.25,100.50,150.75])
gst_pt=0.25
gst_price_pt=gst_pt*cost_pt
total_price_pt=gst_price_pt+cost_pt
print("Cost :\n",cost_pt.tolist())
print("Gst:\n",gst_pt)
print("Gst Price:\n",gst_price.tolist())
print("Total Price:\n",total_price_pt.tolist())

Cost :
 [50.25, 100.5, 150.75]
Gst:
 0.25
Gst Price:
 [360.0, 852.9084, 527.1264]
Total Price:
 [62.8125, 125.625, 188.4375]


### 3. Matrix Multiplication

In [12]:
import numpy as np
price=np.array([
    [100,150,200],
    [50.20,30.56,49.38],
    [200.46,495.4,80.48]
])

price_per_unit=np.array([
    [30.28],
    [50.39],
    [100.25]
])

# Matrix Multiplication
product=price@price_per_unit
product2=np.dot(price,price_per_unit)

print("Product1:\n",product)
print("Product2:\n",product2)

Product1:
 [[30636.5   ]
 [ 8010.3194]
 [39101.2548]]
Product2:
 [[30636.5   ]
 [ 8010.3194]
 [39101.2548]]


In [15]:
import torch
price_pt=torch.tensor([
    [10.5,20.,30.]
]
)

quantity_pt=torch.tensor([
    [2.,3.,4.],
    [8.,9.,7.],
    [7.,5.,6.]
])

# Mulitplication
#prod1=torch.dot(price_pt,quantity_pt)
prod2=torch.matmul(price_pt,quantity_pt)
prod3=price_pt@quantity_pt
#print("Product 1:\n",prod1.tolist())
print("Product 2:\n",prod2.tolist())
print("Product 3:\n",prod3.tolist())

Product 2:
 [[391.0, 361.5, 362.0]]
Product 3:
 [[391.0, 361.5, 362.0]]


### 4.Block Matrices

In [17]:
import numpy as np
a_np=np.array([
    [12,13,14,15],
    [14,15,16,17],
    [10,11,22,33],
    [20,33,44,55]
])

block_1=a_np[1:3:]
block_2=a_np[2:4:2]
print("\n",block_1)
print("\n",block_2)


 [[14 15 16 17]
 [10 11 22 33]]

 [[10 11 22 33]]


## Transpose

In [3]:
import numpy as np
# product-kg & price
A_np=np.array([
    [10,200],
    [5,500],
    [4,350],
])

transpose1=A_np.T
transpose2=np.transpose(A_np)

print("Shape A_np:",A_np.shape)
print("A_np:\n",A_np)

print("Transpose1:\n",transpose1)
print("Transpose1 shape:",transpose1.shape)

print("Transpose2:\n",transpose2)
print("Transpose2 shape:",transpose2.shape)

Shape A_np: (3, 2)
A_np:
 [[ 10 200]
 [  5 500]
 [  4 350]]
Transpose1:
 [[ 10   5   4]
 [200 500 350]]
Transpose1 shape: (2, 3)
Transpose2:
 [[ 10   5   4]
 [200 500 350]]
Transpose2 shape: (2, 3)


### Transpose Operation
**Double Transpose**
$$(A^T)^T = A$$

In [5]:
import numpy as np

# Product--Stock & Quantity
B_np=np.array([
    [20,30],
    [40,50],
    [100,200]
])

# transpose
transpose_B=B_np.T
print("Original Matrix Shape:",B_np.shape)
print("Original Matrix:\n",B_np)

print("Transpose1 Shape:",transpose_B.shape)
print("single Transpose:\n",transpose_B)

# Double Transpose
double_transpose=transpose_B.T
print("Double transpose shape:",double_transpose.shape)
print("Double transpose or original matrix:\n",double_transpose)

Original Matrix Shape: (3, 2)
Original Matrix:
 [[ 20  30]
 [ 40  50]
 [100 200]]
Transpose1 Shape: (2, 3)
single Transpose:
 [[ 20  40 100]
 [ 30  50 200]]
Double transpose shape: (3, 2)
Double transpose or original matrix:
 [[ 20  30]
 [ 40  50]
 [100 200]]


**sum of transpose**
$$(A + B)^T = A^T + B^T$$

In [7]:
import numpy as np
C_np=np.array([
    [4,10],
    [8,20],
    [12,30]
])

D_np=np.array([
    [2,8],
    [4,12],
    [7,15]
])

# Single Transpose 
transpose_C=C_np.T
transpose_D=D_np.T

transpose_sum_C_D=transpose_C+transpose_D
C_D=C_np+D_np
transpose_C_D=C_D.T

print("shape transpose_c:",transpose_C.shape)
print("Transpose C:\n",transpose_C)
print("shape transpose_d:",transpose_D.shape)
print("Transpose D:\n",transpose_D)

print("Shape of sum of transpose:",transpose_sum_C_D.shape)
print("Sum of Transpose:\n",transpose_sum_C_D)

print("shape of sum Transpose C_D:\n",transpose_C_D.shape)
print("Sum of C_np+D_np then Transpose:\n",transpose_C_D)

print(transpose_sum_C_D is transpose_C_D)
print(transpose_sum_C_D== transpose_C_D)

shape transpose_c: (2, 3)
Transpose C:
 [[ 4  8 12]
 [10 20 30]]
shape transpose_d: (2, 3)
Transpose D:
 [[ 2  4  7]
 [ 8 12 15]]
Shape of sum of transpose: (2, 3)
Sum of Transpose:
 [[ 6 12 19]
 [18 32 45]]
shape of sum Transpose C_D:
 (2, 3)
Sum of C_np+D_np then Transpose:
 [[ 6 12 19]
 [18 32 45]]
False
[[ True  True  True]
 [ True  True  True]]
